---
# Tasks for systemd-unit

- name: "Копируем systemd-unit в /etc/systemd/system"
  template:
    src: myapp.j2
    dest: /etc/systemd/system/myapp.service
    owner: root
    group: root
  notify:
    - Start myapp
