---
# Playbook with tasks for GuestBook https://github.com/murik099/rpd_test

- hosts: node1
  become: yes
  vars_files:
    - ./vars/app_params.yml
  roles:
    - nginx-install
    - docker-install
    - app-init
    - mysql-install
    - systemd-unit